name: nick young
output: build
static_src: static
static_dest: "."

partials:
    header: views/partials/header.tmpl
    footer: views/partials/footer.tmpl
    transitions: views/partials/transitions.tmpl
    postheader: views/partials/postheader.tmpl

pages:
    - title: home
      path: /
      template: views/index.tmpl
      data:
          notes: data/notes/notes.yaml

collections:
    - title: notes
      path: /notes
      template: views/post.tmpl
      posts: posts
